### ISSUE TITLE
API shows no recent data

### ISSUE THREAD

**Issue by matiaslee** [developmentseed/landsat-util#252]
Hi people, 

API shows no recent data, example: 
```
$ landsat search -p 229,82 --latest 1
{
    "limit": 25, 
    "results": [
        {
            "cloud": 32.78, 
            "date": "2018-04-30", 
            "path": "229", 
            "row": "082", 
            "sat_type": "L8", 
            "sceneID": "LC82290822018120LGN00", 
            "thumbnail": "https://earthexplorer.usgs.gov/browse/landsat_8/2018/229/082/LC08_L1GT_229082_20180430_20180430_01_RT.jpg"
        }
    ], 
    "status": "SUCCESS", 
    "total": 19, 
    "total_returned": 1
}
['Search completed!']
```
On the other hand, in https://earthexplorer.usgs.gov/ I can see three new tiles with acquisition date May 16th, Jun 1fst, Jun 17th. 

![landsat_bug](https://user-images.githubusercontent.com/22818203/42134258-50e0c494-7d0e-11e8-97c6-033565de3fbf.png)

The request done to the api is: 

https://api.developmentseed.org/satellites/landsat?search=acquisitionDate:[2017-07-01+TO+2018-07-01]+AND+cloud_coverage:[-1+TO+100.0]+AND+((path:229+AND+row:82))&limit=1

Changing the start of the acquisitionDate to 2018-5-1 shows no results.  

https://api.developmentseed.org/satellites/landsat?search=acquisitionDate:[2018-05-01+TO+2018-07-01]+AND+cloud_coverage:[-1+TO+100.0]+AND+((path:229+AND+row:82))&limit=1

Same happens for other tiles, for example 22,37. 

Any help will be appreciated. Thanks in advance!

Matias

**Comment by matthewhanson** [comment]
This has been fixed in the sat-api version that landsat-util uses:
https://medium.com/devseed/sat-api-an-api-for-spatiotemporal-asset-catalogs-88c3c78fdb0e
Please note we also have a new sat-api (although landsat-util will continue to use the old version and will soon be deprecated).

**Comment by matiaslee** [comment]
Congratulation for the new development! We will move to sat-api as soon as possible! 

Ahh, I confirm the old api is working. 

Best!

**Comment by matiaslee** [comment]
Hi Matthew!

I think the problem persist :( The next query shows one result with date 2018-07-03:

https://api.developmentseed.org/satellites/landsat?search=acquisitionDate:[2018-07-01+TO+2018-08-15]+AND+cloud_coverage:[-1+TO+100.0]+AND+((path:229+AND+row:82))&limit=5

And using https://earthexplorer.usgs.gov/ I can see this result and two other ones (2018-07-19 and 2018-08-04)

I've tried to reproduce the query in the new api with no success. This is what I tried: 

https://sat-api.developmentseed.org/search/stac?datetime=2018-07-01/2018-08-15&collection=landsat-8&landsat:path=229&landsat:row=82&limit=10

I this case I only see products from sentinel. Is this an issue in the new api? Or probably I am miss something.

Thanks!

Matias
